config/SZBE69/splits.txt
configure.py
src/rb3/arkfile.cpp
src/rb3/arkfile.hpp

names courtesy of dolmatch lol

Two ArkFile functions

---

config/SZBE69/splits.txt
configure.py
src/rb3/arkfile.cpp
src/rb3/arkfile.hpp
src/rb3/filegetext.cpp
src/rb3/thegame.hpp

in all:
- two ArkFile methods, one of which being a stub
- a nonmatching C function for getting file extensions
- a couple .data labels in TheClass style, courtesy of the dolmatch results

Various changes

---

config/SZBE69/splits.txt
configure.py
src/rb3/data.hpp
src/rb3/netstream.cpp
src/rb3/netstream.hpp
src/rb3/unk_8000D980.cpp
src/rb3/unk_80313E98.cpp
src/rb3/unk_80322664.cpp

no actual functions, sorry; also the enums in data.hpp not being accurate was annoying

Add NetStream class structure

---

config/SZBE69/splits.txt
configure.py
src/RVL_SDK/revolution/rvl/so.h
src/rb3/data.hpp
src/rb3/networksocket.hpp
src/rb3/wiinetworksocket.cpp
src/rb3/wiinetworksocket.hpp

oops i didn't remove wiinetworksocket.cpp:.data, pls do that prior to merging

WiiNetworkSocket partly matched

---

config/SZBE69/splits.txt
configure.py
src/common.hpp
src/rb3/Rnd/rndbitmap.cpp
src/std_native/new
src/std_native/src/new.cpp
src/stlport/README
src/stlport/stlport/stl/_alloc.h
src/stlport/stlport/stl/config/features.h

New/delete operators don't fully match since they're getting merged with each other :/
StlNodeAlloc may need additional work in the future, but it should be overall correct.

StlNodeAlloc and new/delete operators

---

config/SZBE69/splits.txt
configure.py
src/rb3/datautil.cpp
src/rb3/datautil.hpp
src/rb3/gamemode.cpp
src/rb3/gamemode.hpp
src/rb3/hmx/object.hpp
src/rb3/messages.hpp
src/rb3/messages/modechangedmsg.hpp
src/rb3/platformmgr.hpp
src/rb3/system.cpp
src/rb3/system.hpp
src/rb3/trainingmgr.cpp
src/rb3/uipanel.hpp

should be ready to link, but objdiff kinda died on me so I couldn't do so myself lol

Implement GameMode

---

.clang-format
src/rb3/unknown/800/unk_800DB160.cpp
src/rb3/unknown/802/unk_802DDEA0.cpp

clang-format broke all of the asm blocks in src/rb3 lol

Fix and prevent incorrect formatting of asm blocks

---

config/SZBE69_B8/objects.json
src/sdk/RVL_SDK/revolution/os/__ppc_eabi_init.h
src/system/obj/Data.h
src/system/obj/Object.h
src/system/obj/PropSync.cpp
src/system/obj/PropSync_p.h
src/system/obj/TextFile.cpp
src/system/obj/TextFile.h
src/system/os/CritSec.cpp
src/system/os/CritSec.h
src/system/os/Debug.h
src/system/os/File.h
src/system/os/JoypadClient.cpp
src/system/os/JoypadClient.h
src/system/os/JoypadMsgs.cpp
src/system/os/JoypadMsgs.h
src/system/os/MapFile_Wii.cpp
src/system/os/MapFile_Wii.h
src/system/os/NetworkSocket_Wii.cpp
src/system/os/NetworkSocket_Wii.h
src/system/os/UsbMidiGuitarMsgs.cpp
src/system/os/UsbMidiGuitarMsgs.h
src/system/os/UsbMidiKeyboardMsgs.h
src/system/os/User.h
src/system/os/VirtualKeyboard.cpp
src/system/os/VirtualKeyboard.h
src/system/utl/Str.h

NOTE: Although the build passes, I'm getting errors for several TUs (see DataArray.cpp and VirtualKeyboard.cpp) that MSL_C's stdlib is overloading stuff from stlport's stdlib...idk how to fix that

Match some more stuff

---

config/SZBE69_B8/objects.json
src/system/meta/Achievements.cpp
src/system/rndobj/Console.cpp
src/system/utl/BinStream.h
src/system/utl/ChunkStream.cpp
src/system/utl/ChunkStream.h
src/system/utl/Compress.cpp

someone pls do cheevos::handle, it's annoying as fuck

ChunkStream structuring

---

config/SZBE69_B8/objects.json
src/system/math/Decibels.cpp
src/system/math/MathFuncs.h
src/system/math/strips/Striper.cpp
src/system/obj/DataFunc.cpp
src/system/obj/DataFunc.h
src/system/obj/DataNode.cpp
src/system/obj/DataUtl.cpp
src/system/obj/DataUtl.h
src/system/obj/Object.cpp
src/system/obj/Object.h
src/system/os/Debug.cpp
src/system/os/Debug.h
src/system/os/System.h
src/system/utl/BinStream.cpp
src/system/utl/Locale.h
src/system/utl/Magnu.cpp
src/system/utl/Magnu.h
src/system/utl/MakeString.cpp
src/system/utl/MemMgr.h

TUs that are nearly 100%, but have regswaps/other dumb mismatches:
- DataNode
- Magnu
- MakeString
- RevisitedRadix
- Striper
- Sort
- Interp
- Rand
- Decibels

A buncha work on a buncha TUs

---

src/system/meta/Achievements.cpp

Clean up the Achievement Handler syntax

---

config/SZBE69_B8/objects.json
src/band3/game/FretHand.cpp
src/band3/game/FretHand.h
src/system/beatmatch/Output.cpp
src/system/utl/MemStream.cpp
src/system/utl/MemStream.h
src/system/utl/Profiler.cpp
src/system/utl/Profiler.h

Match Output.cpp
memstream uses vector :(

various things

---

.vscode/settings.json
config/SZBE69_B8/objects.json
src/App.cpp
src/App.h
src/band3/meta_band/NameGenerator.cpp
src/band3/meta_band/NameGenerator.h
src/system/milo_types.h
src/system/os/Debug.h
src/system/rndobj/Bitmap.h
src/system/rndobj/Tex.cpp
src/system/rndobj/Tex.h
src/system/rndobj/Trans.cpp
src/system/rndobj/Trans.h
src/system/ui/UIPanel.cpp
src/system/ui/UIPanel.h
src/system/utl/Loader.h

also fixed the vscode editor config to use 4 spaces instead of 2 cause that was annoying

Various TU work

---

config/SZBE69_B8/objects.json
src/system/beatmatch/BeatMatch.cpp
src/system/midi/DataEvent.h
src/system/midi/MidiParser.cpp
src/system/midi/MidiParser.h
src/system/milo_types.h
src/system/obj/ObjPtr_p.h
src/system/rndobj/Bitmap.cpp
src/system/rndobj/Bitmap.h
src/system/rndobj/Console.h
src/system/rndobj/Draw.h
src/system/rndobj/Fur.cpp
src/system/rndobj/Fur.h
src/system/rndobj/Part.h
src/system/rndobj/Set.h
src/system/rndobj/Tex.cpp
src/system/rndobj/Trans.h
src/system/rndobj/Wind.h
src/system/utl/ChunkStream.cpp
src/system/utl/ChunkStream.h
src/system/utl/MemMgr.h

6 TUs edited, only one matched, I'll admit a good chunk of this is only header stuff

so many TUs. so little matched

---

config/SZBE69_B8/objects.json
src/system/char/CharEyeDartRuleset.cpp
src/system/char/CharEyeDartRuleset.h
src/system/char/CharInterest.cpp
src/system/char/CharInterest.h
src/system/char/CharPollable.h
src/system/char/CharTaskMgr.cpp
src/system/char/CharTaskMgr.h
src/system/char/CharWeightable.cpp
src/system/char/CharWeightable.h
src/system/char/ClipCompressor.cpp
src/system/math/Mtx.h
src/system/meta/ConnectionStatusPanel.cpp
src/system/meta/ConnectionStatusPanel.h
src/system/obj/Msg.cpp
src/system/obj/Msg.h
src/system/obj/MsgSource.h
src/system/obj/ObjPtr_p.h
src/system/obj/Object.h
src/system/os/ContentMgr.h
src/system/os/PlatformMgr.h
src/system/os/UserMgr.h
src/system/rndobj/Poll.cpp
src/system/rndobj/Poll.h
src/system/rndobj/Trans.h
src/system/utl/SuperFormatString.cpp

Note: ConnectionStatusPanel (and I anticipate more TUs in the future) is having link issues due to the autogenned inheritance-related symbols appearing in a different order than the target asm dictates

Match a few more TUs yay

---

config/SZBE69_B8/objects.json
src/system/rndobj/Tex.h
src/system/ui/UIComponent.h
src/system/ui/UIPicture.cpp
src/system/ui/UIPicture.h
src/system/utl/Loader.h

something's fucky with the inheritance

uipicture shit

---

config/SZBE69_B8/objects.json
src/system/bandobj/BandCamShot.cpp
src/system/bandobj/VocalTrackDir.cpp
src/system/obj/ObjPtr_p.h
src/system/rndobj/EventTrigger.cpp
src/system/rndobj/Group.cpp
src/system/rndobj/Group.h
src/system/rndobj/Lit.cpp
src/system/rndobj/Lit.h
src/system/rndobj/Mat.h
src/system/rndobj/MotionBlur.cpp
src/system/rndobj/TexBlender.cpp
src/system/rndobj/TexBlender.h
src/system/ui/UIList.cpp

ObjPtrList "work"

---

config/SZBE69_B8/objects.json
src/system/obj/Object.h
src/system/os/JoypadMsgs.h
src/system/rndobj/Trans.h
src/system/ui/Screenshot.cpp
src/system/ui/UIButton.cpp
src/system/ui/UIButton.h
src/system/ui/UIComponent.cpp
src/system/ui/UIComponent.h
src/system/ui/UILabel.cpp
src/system/ui/UILabel.h
src/system/ui/UIPicture.h

More UI work

---

src/system/obj/ObjPtr_p.h

maybe someday we'll actually match this class :,)

Integrate ObjPtrList work up to this point

---

config/SZBE69/flags.json
config/SZBE69/objects.json
config/SZBE69_B8/flags.json
doc/stdlib_test.h
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/extras.h
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/imaxdiv_def.h
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/intmax_def.h
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/complex.h
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/inttypes.h
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/stdint.h
src/system/beatmatch/RGState.cpp
src/system/math/Color.h
src/system/math/Primes.cpp
src/system/math/strips/StdAfx.h
src/system/obj/DataNode.cpp
src/system/obj/Dir.h
src/system/obj/Object.h
src/system/os/Debug.h
src/system/stlport/stl/_map.h
src/system/synth/ByteGrinder.cpp
src/system/utl/HxGuid.h
src/system/utl/Messages.h
src/system/utl/TempoMap.cpp

A fix for `DataNode::Load`, matched `ByteGrinder::Init`, matched retail `json-c` and fixed flags for debug, updated/fixed `stdlib_test.h`, and removed incorrect `-func_align 4` flag in debug.

Fix all compile warnings; other things I've had sitting around

---

config/SZBE69_B8/objects.json
src/KeyChain.h
src/keygen_wii.cpp
src/macros.h
src/system/math/strips/Striper.cpp
src/system/math/strips/Striper.h
src/system/meta/WiiProfileMgr.h
src/system/obj/Object.h
src/system/os/Joypad_Wii.h
src/system/os/PlatformMgr.h
src/system/os/User.cpp
src/system/os/User.h
src/system/rndobj/Anim.h
src/system/rndobj/Mat.cpp
src/system/rndobj/Mat.h
src/system/rndobj/Tex.h
src/system/ui/Screenshot.cpp
src/system/ui/UI.h
src/system/ui/UIButton.cpp
src/system/ui/UIListArrow.cpp
src/system/ui/UIListArrow.h
src/system/ui/UITransitionHandler.cpp
src/system/ui/UITransitionHandler.h
src/system/utl/Profiler.cpp
src/system/utl/Str.cpp
src/system/utl/Str.h
src/system/utl/StringTable.cpp
src/system/utl/StringTable.h

keygen, Str, User, ConnectionStatusPanel, UITransitionHandler
the entire Striper library is also close, just regswaps in 2 functions

Match a bunch of TUs

---

src/system/obj/DataFile.h
src/system/obj/DataFunc.cpp
src/system/obj/Utl.h
src/system/os/Debug.h
src/system/os/File.h
src/system/rndobj/Graph.cpp
src/system/rndobj/Graph.h

bunch of other DataFunc stuff as well

DataInitFuncs done

---

src/system/obj/ObjPtr_p.h
src/system/obj/ObjectStage.h
src/system/rndobj/PropKeys.cpp
src/system/rndobj/PropKeys.h
src/system/utl/BinStream.h
src/system/utl/Key.h

wow PropKeys actually isn't nearly as scary as I thought it'd be

PropKeys and BinStream work

---

src/system/stlport/stl/_alloc.h
src/system/stlport/stl/_uninitialized.h
src/system/stlport/stl/_vector.c
src/system/stlport/stl/_vector.h
src/system/utl/BinStream.h
src/system/utl/MemStream.cpp

*Someone* (me) forgot `auto` isn't a thing in our C++ version lol

Fix various vector compile errors; BinStream operator>>(vector<T>) and MemStream constructor

---

src/system/rndobj/PropKeys.cpp
src/system/rndobj/PropKeys.h
src/system/utl/BinStream.h
src/system/utl/Key.h

More Keys/PropKeys work

---

src/system/obj/Object.cpp
src/system/obj/Utl.cpp
src/system/utl/BeatMap.cpp
src/system/utl/BeatMap.h
src/system/utl/BinStream.h
src/system/utl/BufStream.h
src/system/utl/ChunkStream.cpp
src/system/utl/ChunkStream.h
src/system/utl/Chunks.h
src/system/utl/FileStream.cpp
src/system/utl/FileStream.h
src/system/utl/MemStream.cpp
src/system/utl/MemStream.h
src/system/utl/SongInfoCopy.cpp

MemStream, BeatMap, BinStream and its derivatives, SongInfoCopy

A little bit of work across misc TUs

---

Doxyfile
config/SZBE69_B8/flags.json
config/SZBE69_B8/objects.json
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/buffer_io.c
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/errno.c
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_acos.c
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_asin.c
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_atan2.c
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_exp.c
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_fmod.c
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_log.c
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_log10.c
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_pow.c
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/fdlibm.h
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/PPC_EABI/math_ppc.c
src/sdk/PowerPC_EABI_Support/MSL/MSL_C/PPC_EABI/time.dolphin.c
src/sdk/RVL_SDK/revolution/os/OSMutex.h
src/system/bandobj/CrowdAudio.cpp
src/system/bandobj/CrowdAudio.h
src/system/os/Archive.cpp
src/system/os/Archive.h
src/system/os/NetStream.cpp
src/system/os/NetStream.h
src/system/synth/BinkClip.h
src/system/utl/BinStream.h

sdk stuff, doxygen update, fix hugh

---

config/SZBE69_B8/objects.json
src/system/meta/ConnectionStatusPanel.cpp
src/system/os/AppChild.cpp
src/system/os/Archive.cpp
src/system/os/Archive.h
src/system/os/ArkFile.cpp
src/system/os/ArkFile.h
src/system/os/AsyncFile.cpp
src/system/os/AsyncFile.h
src/system/os/BlockMgr.h
src/system/os/CDReader.cpp
src/system/os/CDReader.h
src/system/os/File.cpp
src/system/os/File.h
src/system/os/FileCache.h
src/system/os/NetworkSocket.h
src/system/os/PlatformMgr.cpp
src/system/os/PlatformMgr.h
src/system/os/System.cpp
src/system/os/System.h
src/system/os/UserMgr.h
src/system/utl/Option.cpp

-Archive
-ArkFile
-MemStream
-Option
also worked a bit on AsyncFile/File/PlatformMgr

Nearly (but not fully 😞 ) match a bunch of TUs

---

config/SZBE69_B8/objects.json
config/SZBE69_B8/splits.txt
src/sdk/RVL_SDK/revolution/base/PPCArch.h
src/sdk/RVL_SDK/revolution/rvl/so.h
src/sdk/RevoEX/src/so/SOBasic.c
src/sdk/RevoEX/src/so/SOCommon.c
src/system/math/Sqrt_Wii.c
src/system/obj/DataFile.h
src/system/obj/DataFunc.h
src/system/obj/DataUtl.cpp
src/system/obj/DataUtl.h
src/system/obj/Dir.h
src/system/obj/Msg.cpp
src/system/obj/Object.cpp
src/system/obj/Object.h
src/system/obj/PropSync_p.h
src/system/obj/TextFile.h
src/system/os/PlatformMgr.h
src/system/os/System.h
src/system/os/System_Wii.cpp
src/system/ui/UIButton.cpp
src/system/utl/Compress.cpp
src/system/utl/Loader.h

matched:
- Compress.cpp
- Sqrt_Wii.c (had to use asmblock, in my defense how tf is frsqrte supposed to naturally generate)

0.01% :POGGERS:

---

configure.py
tools/project.py

PR'ed our modifications to dtk-template and made some requested changes; with this our project.py now matches the template exactly.

Sync project.py with upstream again

---

src/system/char/Character.cpp
src/system/obj/Dir.cpp
src/system/obj/Dir.h
src/system/obj/DirLoader.cpp
src/system/obj/DirLoader.h
src/system/obj/ObjMacros.h
src/system/obj/ObjPtr_p.h
src/system/obj/ObjVersion.h
src/system/obj/Object.h
src/system/obj/PropSync.cpp
src/system/obj/PropSync_p.h
src/system/obj/Utl.cpp
src/system/obj/Utl.h
src/system/os/Debug.h
src/system/os/System.cpp
src/system/os/System.h
src/system/ui/UILabelDir.cpp
src/system/ui/UILabelDir.h
src/system/ui/UIScreen.cpp
src/system/utl/FilePath.h
src/system/utl/Loader.h
src/system/utl/MakeString.h
src/system/utl/UTF8.cpp

- UIScreen is basically good to go except for some stlport related regswap jank
- ObjVersion/sRevStack work (anyone wanna take a look at PopRev pls thnx)
- refactored Object.h, Dir.h, DirLoader.h and ObjPtr_p.h in order to fix circular dependencies needed to implement functions in obj/Utl and DirLoader as a whole
- some work on DirLoader methods

lotsa stuff

---

config/SZBE69_B8/objects.json
src/system/meta/FixedSizeSaveableStream.h
src/system/obj/DataFile.h
src/system/obj/Dir.cpp
src/system/obj/Dir.h
src/system/obj/DirItr.h
src/system/obj/ObjMacros.h
src/system/obj/Object.h
src/system/obj/PropSync_p.h
src/system/os/Debug.cpp
src/system/os/Debug.h
src/system/os/File.cpp
src/system/os/System.h
src/system/synth/Pollable.cpp
src/system/synth/Pollable.h
src/system/ui/UIPanel.h
src/system/utl/HxGuid.cpp
src/system/utl/KeylessHash.h
src/system/utl/Loader.cpp
src/system/utl/Loader.h
src/system/utl/MemMgr.h
src/system/utl/MemcardBufStream.cpp

it's been a while since we've matched something, this feels good

Match UIPanel, HxGuid, MemcardBufStream

---

config/SZBE69_B8/objects.json
src/system/math/Mtx.h
src/system/meta/Profile.cpp
src/system/meta/Profile.h
src/system/obj/Object.h
src/system/obj/Task.h
src/system/rndobj/Console.cpp
src/system/rndobj/CubeTex.cpp
src/system/rndobj/CubeTex.h
src/system/rndobj/Mesh.cpp
src/system/rndobj/Movie.cpp
src/system/rndobj/PropKeys.cpp
src/system/rndobj/SoftParticles.cpp
src/system/rndobj/Tex.h
src/system/rndobj/TransAnim.cpp
src/system/rndobj/TransAnim.h
src/system/ui/UIButton.h
src/system/ui/UILabel.cpp
src/system/ui/UILabel.h

- Link issues related to autogenned virtual/multiple inheritance function ordering seems to have been fixed (I swapped the virtual function ordering of Hmx::Object around and made some autogenned functions "weak"), and as a result I was able to link RndMovie, RndTransProxy and RndSoftParticles
- RndCubeTex is almost ready to go, but like UIScreen and FxSendMeterEffect, there's some stlport regswap jank
- also was able to match Profile, cuz why not right

Fix up some of the link issues we've been having

---

config/SZBE69_B8/objects.json
src/system/char/CharHair.h
src/system/meta/SongMgr.cpp
src/system/meta/SongMgr.h
src/system/meta/SongPreview.cpp
src/system/meta/SongPreview.h
src/system/obj/Msg.cpp
src/system/obj/ObjPtr_p.h
src/system/obj/ObjVector.h
src/system/obj/Object.cpp
src/system/obj/PropSync_p.h
src/system/obj/Task.h
src/system/os/ContentMgr.h
src/system/os/HolmesKeyboard.cpp
src/system/os/HolmesKeyboard.h
src/system/os/VirtualKeyboard.cpp
src/system/os/VirtualKeyboard.h
src/system/os/VirtualKeyboard_Wii.cpp
src/system/rndobj/Anim.cpp
src/system/rndobj/Anim.h
src/system/rndobj/EventTrigger.cpp
src/system/rndobj/Utl.cpp
src/system/synth/Faders.h
src/system/synth/FxSend.cpp
src/system/synth/MicNull.cpp
src/system/synth/MicNull.h
src/system/synth/StandardStream.h
src/system/synth/Stream.h

also matched a few more TUs, so that's cool

meta and RndAnimatable work

---

config/SZBE69_B8/objects.json
src/App.cpp
src/system/char/CharHair.cpp
src/system/char/CharHair.h
src/system/obj/Dir.cpp
src/system/obj/Dir.h
src/system/obj/DirItr.h
src/system/obj/ObjPtr_p.h
src/system/rndobj/AnimFilter.cpp
src/system/rndobj/AnimFilter.h
src/system/rndobj/MotionBlur.cpp
src/system/rndobj/MotionBlur.h
src/system/rndobj/Utl.h
src/system/utl/KeylessHash.h
src/system/utl/Symbol.cpp
src/system/world/CameraShot.cpp
src/system/world/CameraShot.h

- (hopefully) resolved all regswaps/jank for ObjPtrList!!!
- implemented ObjDirItr!!!
- matched RndMotionBlur!!!

we're so back

---

config/SZBE69_B8/objects.json
src/system/os/Keyboard.cpp
src/system/os/Keyboard.h
src/system/rndobj/Tex.cpp
src/system/rndobj/Tex.h
src/system/rndobj/TexBlender.h
src/system/synth/Faders.cpp
src/system/utl/CacheMgr.cpp
src/system/utl/CacheMgr.h
src/system/utl/CacheMgr_Wii.h
src/system/utl/FilePath.h

NOTE: most of the link issues we still have, have something to do with how we've implemented SetType (mainly SetType's bss) - figure that out and our % is gonna shoot up

Fixed a few TUs that had link issues

---

config/SZBE69_B8/flags.json
config/SZBE69_B8/objects.json
src/App.cpp
src/BudgetScreen.cpp
src/BudgetScreen.h
src/band3/game/SongDB.h
src/band3/meta_band/BandSongMgr.h
src/system/beatmatch/SongData.h
src/system/char/CharDriver.cpp
src/system/char/CharFaceServo.cpp
src/system/obj/DataFunc.cpp
src/system/obj/ObjMacros.h
src/system/obj/Task.h
src/system/os/Debug.h
src/system/os/HolmesClient.cpp
src/system/os/Timer.h
src/system/rndobj/Cam.cpp
src/system/rndobj/Rnd.cpp
src/system/rndobj/Rnd.h
src/system/rndobj/ScreenMask.cpp
src/system/rndobj/Utl.cpp
src/system/synth/StandardStream.h
src/system/utl/BinStream.cpp

Also, some notable global changes:
- Fixed DebugNotifyOncer and added a new `MILO_NOTIFY_ONCE` macro (replacing `WARN_ONCE`).
- Renamed `TIMER_THING` macros to be more descriptive, and adjusted `TIMER_THING_NODEL` (now `START_AUTO_TIMER`) to not take a second argument.

Start work on BudgetScreen

---

config/SZBE69_B8/objects.json
src/system/meta/DataArraySongInfo.cpp
src/system/meta/DataArraySongInfo.h
src/system/meta/FixedSizeSaveable.cpp
src/system/meta/FixedSizeSaveable.h
src/system/meta/FixedSizeSaveableStream.cpp
src/system/meta/FixedSizeSaveableStream.h
src/system/meta/SongMetadata.cpp
src/system/meta/SongMetadata.h
src/system/meta/SongMgr.cpp
src/system/meta/SongMgr.h
src/system/meta/SongPreview.cpp
src/system/meta/SongPreview.h
src/system/os/ContentMgr.cpp
src/system/os/ContentMgr.h
src/system/os/Debug.h
src/system/utl/BinStream.h
src/system/utl/CacheMgr.h
src/system/utl/CacheMgr_Wii.h
src/system/utl/MultiTempoTempoMap.cpp
src/system/utl/MultiTempoTempoMap.h
src/system/utl/SongInfoCopy.cpp
src/system/utl/SongInfoCopy.h
src/system/utl/StringTable.cpp
src/system/utl/StringTable.h
src/system/utl/Symbol.cpp
src/system/utl/Symbol.h

-matched: StringTable, SongMetadata
-nearly matched: Symbol, SongMgr, SongPreview, FixedSizeSaveable

a lot really

---

config/SZBE69_B8/objects.json
src/system/movie/Movie.h
src/system/movie/TexMovie.cpp
src/system/utl/BinStream.h
src/system/utl/FilePath.h

TexMovie is kil

---

src/system/rndobj/Dir.cpp
src/system/rndobj/Trans.cpp
src/system/rndobj/Trans.h
src/system/rndobj/Utl.h
src/system/track/TrackDir.cpp
src/system/track/TrackDir.h
src/system/track/TrackTest.h
src/system/track/TrackWidget.h
src/system/ui/UIListDir.cpp
src/system/ui/UIListDir.h
src/system/ui/UIListState.h
src/system/utl/STLHelpers.h

-RndDir is also very close
-UILabelDir needs some stlport regswaps addressed and then it's ready to match

Almost done with PanelDir, UIListDir and TrackDir

---

src/system/stlport/stl/_alloc.h
src/system/stlport/stl/_bvector.h
src/system/stlport/stl/_deque.h
src/system/stlport/stl/_hashtable.h
src/system/stlport/stl/_list.h
src/system/stlport/stl/_slist.h
src/system/stlport/stl/_string.h
src/system/stlport/stl/_tree.h
src/system/stlport/stl/_vector.h
src/system/stlport/stl/pointers/_deque.h
src/system/stlport/stl/pointers/_list.h
src/system/stlport/stl/pointers/_set.h
src/system/stlport/stl/pointers/_slist.h
src/system/stlport/stl/pointers/_vector.h

Probably the one thing I shouldn't have removed in The Std-ening lol

Restore _STLP_CONVERT_ALLOCATOR usage to fix errors on retail

---

config/SZBE69_B8/objects.json
src/band3/game/TrainerGemTab.cpp
src/band3/game/TrainerGemTab.h
src/system/bandobj/BandLabel.cpp
src/system/bandobj/BandLabel.h

match the 2nd largest function in the RB3 codebase nbd

---

src/system/obj/Dir.cpp

100% according to both ObjDiff and decomp.me (I've had these two differ before for reasons I'm not sure of)
Single-change commit 'cause this is my first time contributing to a decomp project, so I wanted to start with something very small.

Match ObjectDir::HasSubDir

---

config/SZBE69_B8/flags.json
config/SZBE69_B8/objects.json
src/sdk/DWC/dwc_common/dwc_error.c
src/sdk/DWC/dwc_common/dwc_error.h
src/sdk/DWC/dwc_common/dwc_init.c
src/sdk/DWC/dwc_common/dwc_init.h
src/sdk/DWC/dwc_common/dwc_memfunc.c
src/sdk/DWC/dwc_common/dwc_memfunc.h
src/sdk/DWC/dwc_common/dwc_report.c
src/sdk/DWC/dwc_common/dwc_report.h
src/sdk/DWC/dwc_nonport/dwc_nonport.h
src/sdk/DWC/dwcsec_auth/dwc_auth_interface.h
src/sdk/DWC/dwcsec_nas/dwc_naslogin.c
src/sdk/DWC/dwcsec_nas/dwc_naslogin.h
src/sdk/RVL_SDK/revolution/os/OSError.h
src/sdk/RVL_SDK/revolution/os/OSReboot.c

0.03% code
0.05% data
6 files, 5 in DWC
totals: 7.02% code 15.32% data 342 linked files

half of DWC matching

---

config/SZBE69_B8/objects.json
src/system/os/JoypadClient.cpp
src/system/os/JoypadClient.h
src/system/stlport/stl/_algobase.h
src/system/ui/UIListProvider.cpp
src/system/ui/UIListProvider.h

No comment field for UIListProviders LinkIssues status, because I'm not actually sure what the problem is.
Hopefully inlining std::find doesn't turn out to be a catastrophic mistake.

System, UI, and STLPort work - oh my!

---

config/SZBE69_B8/objects.json
src/band3/bandtrack/GemRepTemplate.cpp
src/band3/bandtrack/GemRepTemplate.h
src/system/obj/Data.h
src/system/obj/DataArray.cpp
src/system/rndobj/Mesh.cpp
src/system/rndobj/Mesh.h

namely: GemRepTemplate, messing with DataArray::Load, and fixing VertVector

extra work i did that i forgot to commit

---

config/SZBE69/flags.json
config/SZBE69/objects.json
config/SZBE69/splits.txt
config/SZBE69_B8/objects.json
src/sdk/DWC/dwc_common/dwc_init.c
src/sdk/DWC/dwcsec_auth/dwc_auth_interface.h
src/sdk/DWC/dwcsec_svl/dwc_svl.c
src/sdk/DWC/dwcsec_svl/dwc_svl.h
src/system/math/Decibels.cpp
src/system/os/Debug.cpp

if someone can figure out the regswaps in striper in bank 8 that'd be nice

buncha retail work, some dwc

---

config/SZBE69/objects.json
config/SZBE69/splits.txt
config/SZBE69_B8/objects.json
src/system/bandobj/BandButton.cpp
src/system/bandobj/BandButton.h
src/system/bandobj/BandCamShot.cpp
src/system/bandobj/BandCamShot.h
src/system/bandobj/BandLabel.h
src/system/char/Character.h
src/system/math/Mtx.h
src/system/obj/ObjPtr_p.h
src/system/rndobj/Text.h
src/system/ui/UILabel.h
src/system/world/CameraShot.h

getting ahead of the merge conflicts

Work on BandButton and BandCamShot

---

.vscode/settings.json
config/SZBE69/config.json
config/SZBE69/objects.json
config/SZBE69_B8/config.json
config/SZBE69_B8/objects.json
configure.py
doc/config_schema.json
doc/objects_schema.json
tools/project.py

With some tidy along the way.
`flags.json` is now `config.json`, progress categories are stored there alongside the flag sets. Also improved the JSON schema a little to point out missing required keys.

Pull in latest dtk-template changes; support progress categories

---

config/SZBE69/objects.json
config/SZBE69/splits.txt
src/system/bandobj/ChordShapeGenerator.cpp
src/system/bandobj/ChordShapeGenerator.h
src/system/bandobj/DialogDisplay.cpp
src/system/bandobj/DialogDisplay.h
src/system/bandobj/EndingBonus.cpp
src/system/bandobj/EndingBonus.h
src/system/bandobj/FingerShape.cpp
src/system/bandobj/FingerShape.h
src/system/bandobj/NoteTube.cpp
src/system/bandobj/NoteTube.h
src/system/beatmatch/RGUtl.h
src/system/rndobj/Mesh.cpp
src/system/rndobj/Mesh.h

ChordShapeGenerator got hands oh my

a bit more bandobj work

---

config/SZBE69/objects.json
config/SZBE69/splits.txt
src/band3/bandtrack/GemRepTemplate.cpp
src/system/bandobj/ChordShapeGenerator.cpp
src/system/bandobj/NoteTube.cpp
src/system/char/CharCollide.cpp
src/system/char/Character.cpp
src/system/math/Bsp.h
src/system/math/Color.h
src/system/math/Geo.h
src/system/math/Mtx.h
src/system/math/Vec.h
src/system/math/strips/Striper.h
src/system/os/System.h
src/system/rndobj/Draw.h
src/system/rndobj/Line.cpp
src/system/rndobj/Mat.h
src/system/rndobj/Mesh.cpp
src/system/rndobj/Mesh.h
src/system/rndobj/MeshAnim.cpp
src/system/rndobj/MeshAnim.h
src/system/rndobj/Utl.cpp

meshanim got some serious hands

mesh and meshanim work

---

config/SZBE69_B8/objects.json
src/band3/game/BandUserMgr.h
src/band3/game/Stats.cpp
src/band3/game/Stats.h
src/band3/meta_band/AccomplishmentProgress.cpp
src/band3/meta_band/AccomplishmentProgress.h
src/band3/meta_band/AssetProvider.cpp
src/band3/meta_band/BandProfile.cpp
src/band3/meta_band/BandProfile.h
src/band3/meta_band/MetaPerformer.cpp
src/band3/meta_band/MetaPerformer.h
src/band3/meta_band/PerformanceData.cpp
src/band3/meta_band/PerformanceData.h
src/band3/meta_band/ProfileAssets.h
src/band3/meta_band/SongStatusMgr.h
src/band3/tour/TourBand.h
src/band3/tour/TourCharLocal.h
src/band3/tour/TourProgress.h
src/network/net/NetSession.h
src/system/meta/FixedSizeSaveable.h
src/system/meta/Profile.cpp
src/system/meta/Profile.h

i'm ngl i'm submitting this PR now so that once this and nate's PR are merged, I can work in retail again
yes, i could just rebase...but i don't wanna

PerformanceData and BandProfile work

---

configure.py
doc/objects_schema.json
tools/project.py

Notable changes:
- Introduces `extra_clang_flags` for object configurations.
- Changes default language mode for .c files to C99.
- Fixes objects with no corresponding source file showing as red/diffable in objdiff.

Update project/configure.py from latest dtk-template

---

src/system/obj/Dir.h
src/system/obj/ObjMacros.h
src/system/obj/Object.cpp
src/system/obj/Object.h
src/system/obj/TypeProps.cpp
src/system/obj/Utl.cpp
src/system/world/Instance.cpp

PLEASE read these descriptions and verify whether they're good to go before merging pls thnx

Object-centric documentation

---

src/system/obj/MessageTimer.cpp
src/system/obj/MessageTimer.h
src/system/obj/Msg.cpp
src/system/obj/Object.cpp
src/system/obj/Utl.cpp
src/system/obj/Utl.h
src/system/utl/Loader.cpp
src/system/utl/Loader.h
src/system/utl/MemPoint.h

mainly Utl and Loader/FileLoader

Misc obj folder work

---

src/system/obj/Data.h
src/system/obj/DataArray.cpp
src/system/obj/DataFile.cpp
src/system/obj/DataFile.h
src/system/obj/DataFunc.cpp
src/system/obj/DataFunc.h
src/system/obj/Dir.cpp
src/system/obj/Dir.h
src/system/obj/DirLoader.cpp
src/system/obj/DirLoader.h
src/system/obj/DirUnloader.cpp
src/system/obj/DirUnloader.h
src/system/obj/ObjMacros.h
src/system/obj/ObjPtr_p.h
src/system/obj/Object.cpp
src/system/obj/Object.h
src/system/obj/Utl.cpp
src/system/obj/Utl.h
src/system/os/ThreadCall.h
src/system/rndobj/Anim.cpp
src/system/utl/KeylessHash.h
src/system/utl/Loader.h

-All DataFile functions have implementations (other than ParseNode, everything is either matching or functionally equivalent)
-Document functions for ObjectDir, Object, KeylessHash, and misc funcs in obj/Utl

obj folder work

---

config/SZBE69/objects.json
src/system/obj/Data.h
src/system/obj/Dir.h
src/system/obj/ObjPtr_p.h
src/system/obj/Object.cpp
src/system/obj/Object.h
src/system/rndobj/Anim.h
src/system/rndobj/AnimFilter.cpp
src/system/rndobj/AnimFilter.h
src/system/rndobj/Dir.cpp
src/system/rndobj/Dir.h
src/system/rndobj/Draw.cpp
src/system/rndobj/Draw.h
src/system/rndobj/Group.cpp
src/system/rndobj/Group.h
src/system/rndobj/Poll.h
src/system/rndobj/PollAnim.cpp
src/system/rndobj/PollAnim.h
src/system/rndobj/Set.cpp
src/system/rndobj/Set.h
src/system/rndobj/Utl.h

Documentation added for:
-RndGroup
-RndSet
-RndDir
-RndAnimatable
-RndAnimFilter
-RndDrawable
-RndPollable
-RndPollAnim
-ObjectDir
-Object

RndGroup/Set work, and a buncha documentation

---

config/SZBE69_B8/objects.json
src/system/math/Rot.h
src/system/math/Trig.h
src/system/math/Utl.h
src/system/obj/Data.h
src/system/obj/Object.h
src/system/obj/PropSync_p.h
src/system/os/System.h
src/system/rndobj/Draw.h
src/system/rndobj/Mat.h
src/system/rndobj/MultiMesh.h
src/system/rndobj/MultiMeshProxy.h
src/system/rndwii/Mesh.h
src/system/world/CameraManager.cpp
src/system/world/CameraManager.h
src/system/world/CameraShot.cpp
src/system/world/CameraShot.h
src/system/world/ColorPalette.h
src/system/world/Crowd.cpp
src/system/world/Crowd.h

-implementations and documentation for CameraManager, CamShot and WorldCrowd where able

World folder work

---

.clangd
config/SZBE69_B8/objects.json
src/decomp.h
src/system/math/Utl.h
src/system/obj/DataFunc.cpp
src/system/os/Debug.h

Two functions stand in the way of matching, along with data ordering issues, but the mismatches are equivalent. Everything else is matched 100%.
i had to re-create all the commits to fix them not being signed, so the commit times are inaccurate lol

DataFunc now equivalent

---

config/SZBE69_B8/objects.json
src/band3/game/Stats.h
src/band3/meta_band/BandProfile.cpp
src/band3/meta_band/BandProfile.h
src/band3/meta_band/Instarank.h
src/band3/meta_band/MetaPerformer.cpp
src/band3/meta_band/MetaPerformer.h
src/band3/meta_band/MultiSelectListPanel.cpp
src/band3/meta_band/MultiSelectListPanel.h
src/band3/meta_band/OvershellPanel.cpp
src/band3/meta_band/OvershellPanel.h
src/band3/meta_band/OvershellProfileProvider.h
src/band3/meta_band/OvershellSlot.cpp
src/band3/meta_band/OvershellSlot.h
src/band3/meta_band/ParentalControlPanel.cpp
src/band3/meta_band/ParentalControlPanel.h
src/band3/meta_band/ProfileMgr.h
src/band3/meta_band/SaveLoadManager.h
src/band3/meta_band/Utl.h
src/band3/net_band/RockCentral.h
src/band3/net_band/RockCentralMsgs.h
src/band3/tour/Tour.cpp
src/band3/tour/Tour.h
src/decomp.h
src/system/rndwii/MultiMesh.cpp

also add some context where applicable

Retail symbols for MetaPerformer and OvershellPanel

---

.gitignore

ignore macos .ds_store

---

src/system/bandobj/ArpeggioShape.cpp
src/system/bandobj/BandCamShot.cpp
src/system/obj/Data.h

vetted by @ieee802dot11ac and @rjkiv so its totally legit i promise yo

minor adjustments based off stream (real changes!)

---

src/sdk/PowerPC_EABI_Support/MetroTRK/msg.c
src/sdk/PowerPC_EABI_Support/MetroTRK/target_options.c
src/system/synth/ByteGrinder.cpp

you'd think the first half ones would be easier

bytegrinder *almost* matching

---

config/SZBE69_B8/objects.json
src/sdk/RVL_SDK/revolution/kbd/kbd.h
src/system/os/Keyboard_Wii.cpp
src/system/os/Keyboard_Wii.h

https://github.com/user-attachments/assets/3f6d2be9-aab7-4dd5-bdec-9960f1919a90

match Keyboard_Wii

---

src/network/Platform/InetAddress.cpp
src/network/Platform/InetAddress.h
src/sdk/DWC/dwc_common/dwc_error.h
src/sdk/DWC/dwcsec_prof/dwc_prof.h
src/sdk/RVL_SDK/revolution/os/OSReset.h
src/sdk/RVL_SDK/revolution/rvl/so.h
src/sdk/RVL_SDK/revolution/sc/scapi.h
src/sdk/RVL_SDK/revolution/vi/vi.h
src/system/os/HomeMenu_Wii.h
src/system/os/NetworkSocket_Wii.cpp
src/system/os/PlatformMgr.h
src/system/os/PlatformMgr_Wii.cpp

more wii platform stuff
