.gitignore, .vscode/c_cpp_properties.json
'Cause someone's gotta do it eventually lol
- Fix the include/browse paths in the VS Code C/C++ config
- Tidy up and comment .gitignore to make it more understandable/maintainable
- Add missing .gitkeep for `tools/mwcc_compiler`, was in the .gitignore but not in the repo itself for some reason
- Add general-purpose ignore entries: name a folder `ignore`/`ignored` or suffix a file with `.ignore`/`.ignored` before its extension (e.g. `text.ignored.txt`) to exclude it. Meant for scratch work or temporary items that shouldn't be committed.
=> Fix VS Code config and tidy up .gitignore

configure.py, src/json-c/arraylist.c, src/json-c/arraylist.h, src/json-c/bits.h, src/json-c/debug.c, src/json-c/debug.h, src/json-c/json_object.c, src/json-c/json_object.h, src/json-c/json_object_private.h, src/json-c/json_tokener.c, src/json-c/json_tokener.h, src/json-c/json_util.c, src/json-c/json_util.h, src/json-c/linkhash.c, src/json-c/linkhash.h, src/json-c/printbuf.c, src/json-c/printbuf.h, src/json-c/test1.c, src/json-c/test2.c
Definitely one of the fixes lol
I reformatted everything because the formatting was *atrocious* with the current editor config settings. json-c (the version used here, at least) is intended to have a tab size of 8, but it also uses a mix of spaces and tabs to achieve an effective indentation size of 2: tabs for each multiple of 8, spaces for the rest. Very weird hybrid.
I also can't get json_tokener to link for some reason, linker complains about `isspace` not being defined when linking `fn_8048D200` in `auto_03_80472568.o`. `isspace` is inline and is getting compiled into `json_tokener.o`, which I've verified is correct (it comes right after `json_tokener_parse_ex` in both the original binary and the compiled object), and it is not getting name mangled.
=> Match json_tokener.c, and reformat all of json-c

configure.py, src/json-c/debug.h, src/std/ctype.h, src/types.h
- Remove concat sequence in json-c debug macros to fix `invalid token pasting of ',' and 'tok'` warning
- Remove `size_t` from types.h to prevent re-definition warning, it's already defined by stddef.h
- Remove `static` from ctype.h's inline methods to fix linker errors
=> Fix json-c warnings and link json_tokener

.vscode/c_cpp_properties.json, .vscode/tasks.json, configure.py, decompctx.py, src/std_native/assert.h
A couple growing pains from the new script lol, hopefully there's not much else that needs to be done.
Script adjustments:
- Fix `#include <file>` directives not resolving paths in the same directory as the including file
- Pass through a number of unknown defines to help prevent context being only C or C++ compatible
- Clean up file output a little bit by stripping blank lines and adding a newline before the added `#line` directives
Other changes:
- Add defines list to configure.py, and pull those in decompctx
- Fix `assert` macro not respecting `NDEBUG` define
- Add VS Code task for generating context for the current file
=> More decompctx adjustments

.vscode/launch.json, cflags_common.py, configure.py, decompctx.py
By default, `#define`s are preserved and macros are no longer expanded outside of preprocessor directives. This allows them to still be used in scratches, and generally keeps things more understandable.
There is also now an option to evaluate `__option()` macros such as `__option(longlong)` or `__option(wchar_type)`, for Ghidra or m2c pre-processing.
Before:
After:
=> Better macro handling in context generator

src/RVL_SDK/revolution/ai/ai_hardware.h, src/RVL_SDK/revolution/dsp/dsp_hardware.h, src/RVL_SDK/revolution/exi/EXIHardware.h, src/RVL_SDK/revolution/gx/GXHardware.h, src/RVL_SDK/revolution/ipc/ipcMain.h, src/RVL_SDK/revolution/os/OSHardware.h, src/RVL_SDK/revolution/vi/vihardware.h, src/macros.h
- `ASM_BLOCK` is now defined as just `asm` under MWCC, both `asm{}` and `asm()` are valid forms of asm blocks. Without this, instructions with variable operand counts won't work correctly due to everything being smooshed onto one line without semicolon separation.
- `AT_ADDRESS` is already defined in `revolution/os/OSUtils.h`, we don't need to re-define it ourselves.
- Add `__option` macro stub for VS Code
- Fix invalid array length in `OSHardware.h`
=> Some macro fixes

tools/batch-demangle/Cargo.lock, tools/batch-demangle/Cargo.toml, tools/batch-demangle/src/main.rs, tools/ghidra-scripts/dtk_symbol_importer.py
The demangled name is now split into name and namespaces, with the namespaces being created in Ghidra and converted to classes where possible.
Templates, function pointer types, return types, and parameter types are all handled correctly now in the demangling process. The latter two aren't applied to the program yet however, seems a bit out of scope currently (have to make sure all types are resolved, and determining whether or not a `this` parameter exists is a fool's errand with only MWCC symbols).
=> Ghidra symbol importer upgrades

config/SZBE69/splits.txt, configure.py, src/rb3/Rnd/wii/wiirnd.cpp, src/rb3/Rnd/wii/wiirnd.hpp, src/rb3/hmx/rect.hpp, src/sdk/RVL_SDK/revolution/gx/GXTypes.h
Note: the GX* functions might be off, since the only actual difference is what bit depth is stored at 0xCC008000.
=> Initial WiiRnd work

.vscode/tasks.json, cflags_common.py, config/SZBE69/flags.json, config/SZBE69_B8/flags.json, configure.py, decompctx.py
The base retail flags should be fully restored now, aside from `cflags_c` and its derivatives.
=> Allow specifying compile/link flags per-version

.gitignore, doc/SZBE69_B8_splits_original.txt, tools/splits_fixup.py, tools/splits_generate_sources.py
The original splits file has been preserved in case future structure changes need to be made, though it shouldn't be too difficult to make those changes manually if needed.
The source file generation script outputs the following structure:
- band3
- lib
- binkwii
- network
- sdk
- DWC
- ec
- NdevExi2A
- PowerPC_EABI_Support
- MetroTRK
- MSL
- MSL_C
- MSL_C++
- Runtime
- RevoEX
- RVL_SDK
- system
These loose objects will go into the top-level directory:
- App.cpp
- BandOffline.cpp
- BudgetScreen.cpp
- ChecksumData_wii.cpp
- keygen_wii.cpp
- Main.cpp
=> Fix up splits paths and add script to generate TODO source files from them

.vscode/tasks.json, config/SZBE69_B8/splits.txt, tools/splits_fixup.py
These changes are intended to help with more proper include paths for SDK/library stuff. Using RVL_SDK as an example, the source files are now output to `RVL_SDK/src`, and the existing headers would be separate in the `RVL_SDK/revolution` folder.
I also spotted another variation of `src` in the original paths that wasn't getting stripped out, so I fixed that by using another regex like I originally planned to do.
=> Adjust SDK split file paths a little bit

.vscode/settings.json, .vscode/tasks.json, config/SZBE69/flags.json, config/SZBE69/objects.json, config/SZBE69_B8/flags.json, config/SZBE69_B8/objects.json, configure.py, doc/flags_schema.json, doc/objects_schema.json, tools/project.py
- The cflag system now allows inheriting from another set of cflags. Inheritance is evaluated bottom-up, starting with includes first.
- I reorganized cflags to more easily allow lib-specific optimization flags as needed, and added in a bunch of flag sets for libraries in the project.
- Objects are now specified per-version, since not all objects are compiled the same way on all versions.
- Both the flag and object versioning files now have schemas, for documentation and editor validation support.
- I disabled the `Missing configuration for <...>` logging since all it does for us now is just spam the console when reconfiguring.
- I added another VS Code task for `ninja diff`, and made the `ninja` task the default build task, since that makes more sense than just building the current file.
=> Rework cflags system and make objects be specified per-version

.clang-format
Otherwise one of IntPacker's asserts will get screwed up when formatting.
=> Mark assert macros as whitespace-sensitive in clang-format config

.vscode/c_cpp_properties.json, config/SZBE69/flags.json, config/SZBE69/objects.json, config/SZBE69/splits.txt, config/SZBE69_B8/flags.json, configure.py, decompctx.py, src/macros.h, src/network/net/JsonUtils.cpp, src/network/net/JsonUtils.h, src/system/obj/Object.h, src/system/os/Debug.h, src/system/stlport/stl/_alloc.h, src/system/stlport/stl/_deque.h, src/system/stlport/stl/_list.h, src/system/stlport/stl/_map.h, src/system/stlport/stl/_slist.h, src/system/stlport/stl/_string.c, src/system/stlport/stl/_string.h, src/system/stlport/stl/_tree.h, src/system/stlport/stl/_vector.c, src/system/stlport/stl/_vector.h, src/system/stlport/stl/pointers/_vector.h, src/system/utl/Str.cpp, src/system/utl/Str.h
PR'ing so that this stuff doesn't rot away on my local repo for any longer lol
Vector is still not fully matching, got an annoying regswap in `_M_insert_overflow`. `JsonUtils` would be matching otherwise
---
I added a `MILO_DEBUG` define for the debug macros, so that we can switch back to retail where needed. I also added a `GAME_VERSION` define for any instances where code deviates between builds. It was necessary to fix a vector difference in retail, and will most certainly be necessary in the future.
=> More `vector` progress; a `map` fix; `MILO_DEBUG` and `GAME_VERSION` defines

.vscode/settings.json
These settings don't need to be explicitly forced for the workspace; .editorconfig and formatting will take care of tab size and trailing newlines, and forcing ignore file usage in search off isn't necessary as there's a toggle right in the search menu for it.
=> Remove some more VS Code settings.json entries

config/SZBE69_B8/objects.json, src/system/math/Interp.cpp
No idea what I was doing really. Just fiddled around with data type casting and it got there in the end.
Thanks to Hugh for the last 1% trying to get the `bge` instruction to turn into `bgt` with
```cpp
if(severity > 0.001f) {
} 
else MILO_FAIL("ATanInterpolator: severity (%f) too small.", severity);
```
Don't know if the formatting is correct sometimes my VS Code just doesn't care about running formatters lol.
=> Match system/math/Interp.cpp

config/SZBE69_B8/objects.json, src/system/os/PlatformMgr.cpp, src/system/os/PlatformMgr.h
0.06% code, 1.94% data!
`-ipa file` seems to be the key to all the inline generation reversals we have. It doesn't work when set globally however, causes a ton of link errors, so this was likely hand-set on specific files.
=> Fix and match PlatformMgr

src/system/stlport/stl/_alloc.h
Not all added are technically required, but they might as well be there lol
=> Add missing members to StlNodeAlloc based on C++ standard

config/SZBE69_B8/config.yml, config/SZBE69_B8/objects.json, configure.py, src/system/bandobj/StarDisplay.cpp, src/system/midi/MidiParser.cpp, src/system/obj/ObjPtr_p.h, src/system/obj/PropSync_p.h, src/system/rndobj/CubeTex.cpp, src/system/rndobj/CubeTex.h, src/system/rndobj/Tex.h, src/system/stlport/stl/_vector.h, src/system/stlport/stl/pointers/_list.h, src/system/stlport/stl/pointers/_vector.h, src/system/ui/UIListWidget.cpp, src/system/utl/Loader.h
Fixes yet more STLport issues, with some other miscellaneous stuff.
=> STL my Port

config/SZBE69_B8/flags.json, config/SZBE69_B8/objects.json, src/sdk/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/mem.c, src/sdk/RVL_SDK/revolution/base/PPCArch.c, src/sdk/RevoEX/ssl/ssl_mutex.c, src/system/math/Mtx.h, src/system/math/Rot.cpp, src/system/movie/Movie.h, src/system/movie/TexMovie.cpp, src/system/movie/TexMovie.h, src/system/rndobj/Draw.h, src/system/rndobj/Flare.cpp, src/system/rndobj/Rnd.cpp, src/system/rndobj/Rnd.h
=> TexMovie is evil

config/SZBE69_B8/flags.json, src/network/Platform/MemoryManager.h, src/network/Platform/Result.cpp, src/network/Platform/RootObject.cpp, src/system/math/Sqrt_Wii.c, src/system/midi/MidiReader.cpp, src/system/obj/Object.h, src/system/obj/PropSync_p.h, src/system/obj/TypeProps.cpp, src/system/os/CritSec.h, src/system/os/DateTime.cpp, src/system/os/Debug.cpp, src/system/os/HDCache.h, src/system/os/OSFuncs.h, src/system/os/ProfilePicture.cpp, src/system/os/SynchronizationEvent.h, src/system/os/System_Wii.cpp, src/system/os/ThreadCall.h, src/system/rndobj/MultiMesh.h, src/system/synth/SynthSample.cpp, src/system/utl/Cache.cpp, src/system/utl/Cache_Wii.cpp, src/system/world/CameraShot.h
- Fix a bunch of warnings
- Disable missing-return warning since some spots need a missing return
- Also just causes noise in the output when building, there's a few functions currently which aren't implemented yet
- Enable warning for mismatching capitalization of include filenames
=> Fix warnings again, a small bit of tidy

tools/decompctx.py
No longer strips `__attribute__(())` or `AT_ADDRESS` by default, and no longer converts binary literals by default.
=> Fix decompctx.py stripping some things it shouldn't; some other tidy in it

tools/decompctx.py
What seemed like a harmless change for parity ended up breaking the whole thing. +1 for remembering to test stuff lol
=> Fix decompctx.py throwing an error when used

config/SZBE69_B8/objects.json, src/decomp.h, src/system/obj/Data.h, src/system/obj/DataArray.cpp, src/system/obj/DataFunc.cpp, src/system/obj/DataFunc.h, src/system/os/Timer.h
Some issues still remain, but the functions they affect otherwise appear to be equivalent.
- `DataArray::Execute`: regswaps, `AutoTimer` constructor, `gDataFuncs.find`.
- `DataArray::Load`: regswaps, stackswaps.
=> DataArray.cpp now equivalent

.editorconfig, .vscode/tasks.json
- Rely on .gitattributes to normalize line endings instead of .editorconfig `end_of_line`; avoids annoyances regarding undo/redo stacks getting dropped due to the automatic conversion on save.
- Remove report.json tasks from VS Code config, now that dtk-template generates it naturally through the default Ninja rule.
=> A couple project configuration misc. things

Doxyfile
important: commonly-used base classes (objref) don't flashbang you anymore
graphs are actually reasonable to read
stlport found dead in miami
=> Doxygen improvements

config/SZBE69_B8/objects.json, src/sdk/RVL_SDK/revolution/usb/hid.h, src/system/usbwii/UsbWii.cpp, src/system/usbwii/UsbWii.h
Backbone entertainment decided it was a good idea to have a Sony controller in the whitelist on a Nintendo game and promptly went bankrupt after Nintendo pressed the bankrupt backbone button in retaliation. This plan backfired for Nintendo as gremlins would later find the Backbone Box and take Rock Band out of it.
=> start on UsbWii

src/band3/meta_band/BandSongMetadata.h, src/band3/meta_band/StoreRootPanel.cpp, src/band3/meta_band/StoreRootPanel.h
=> StoreRootPanel partial

src/band3/meta_band/AppLabel.cpp, src/band3/meta_band/AppLabel.h
Surely i will find something to help with author finder in here :clueless:
(Only matches 99% but the mismatch is some string offset I don't know about)
=> AppLabel handlers
